version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: genesys_postgresql
      POSTGRES_PASSWORD: "GeNeAceDgcdaeThc"
      POSTGRES_DB: workflow
    ports:
      - "5432:5433"

  web:
    build: .
    environment:
      DATABASE_URL: "postgresql://genesys_postgresql:GeNeAceDgcdaeThc@dev3-genesys-postgresql-rds.cowisidbp2lg.us-east-1.rds.amazonaws.com:5432/workflow"
    ports:
      - "3000:3000"
    depends_on:
      - db
