version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123#"
      POSTGRES_DB: workflow
    ports:
      - "5432:5433"

  web:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:123%23@db:5433/workflow"
    ports:
      - "3000:3000"
    depends_on:
      - db
